### PR TITLE
Feature update

### PR DESCRIPTION
**Pull request by Lhoerion**
This pull request should fill the gap that exists between TS and .NET languages generator.
Some of the stuff requires also changes in DocFX, which I'm not certain about if they can be implemented in `UniversalReference` or should I actually separate stuff for TypeScript.

### CODE REVIEW

**Comment by yunair** [comment]
Thanks for your pr!
but now, we are moving Universal Reference to sdp, So this version of type2docfx is deprecated.
So we will try to release a  new version. In the future, most of logic will be changed.

**Comment by Lhoerion** [comment]
@yunair Any ETA on when SDP version will appear?

**Comment by yunair** [comment]
we will release new version this month

**Comment by Lhoerion** [comment]
@yunair Is there a possibility to join testing a little bit sooner?

**Comment by yunair** [comment]
Sorry for late reply, We have tested it internally, so the output version is the release version.

**Pull request closed without merging**
